# Generated by Django 4.2.5 on 2023-09-07 10:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('age', models.CharField(max_length=255)),
                ('sex', models.CharField(max_length=255)),
                ('bio', models.TextField()),
                ('image', models.CharField(max_length=255)),
                ('adopted', models.BooleanField()),
                ('gets_along_with_cats', models.BooleanField()),
                ('gets_along_with_dogs', models.BooleanField()),
                ('gets_along_with_children', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=255)),
                ('opening_hours', models.CharField(max_length=255)),
                ('closing_hours', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_cats', models.BooleanField()),
                ('has_dogs', models.BooleanField()),
                ('has_children', models.BooleanField()),
                ('approved_to_adopt', models.BooleanField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('number_of_guests', models.IntegerField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musickittyapi.location')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musickittyapi.profile')),
            ],
        ),
        migrations.CreateModel(
            name='ProfileAdoption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adoption_date', models.DateField()),
                ('status', models.CharField(max_length=255)),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musickittyapi.cat')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musickittyapi.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('price', models.FloatField()),
                ('image', models.CharField(max_length=255)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musickittyapi.location')),
            ],
        ),
        migrations.CreateModel(
            name='CatFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musickittyapi.cat')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musickittyapi.profile')),
            ],
        ),
        migrations.AddField(
            model_name='cat',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musickittyapi.location'),
        ),
    ]
